### ISSUE TITLE
Looking for testers

### ISSUE THREAD

**Issue by tomaae** [tomaae/homeassistant-portainer#1]
If you are interested in testing, let me know here.
Integration wont be added to HACS until it is in decent functionality stage and well tested. So all testing will be done by pulling from github directly.
You can also let me know bit about your setup and what would you like to monitor/automate using HA. It will help with development, as my own requirements for this integration are quite basic.

**Comment by IAmTheMilkManMyMilkIsDelicious** [comment]
I'm running this locally, as I'd love to have some way to monitor my containers and have home assistant notify me when one of them goes down or loses connection. It's working great, simple to set up! :smile: 

One thing that might be nice is to be able to see the health status of a container (based on the healthcheck). Portainer already supports this in the UI, but I'm not sure if it's accessible by API.

**Comment by tomaae** [comment]
could be possible. where do you see it in docker cli?

**Comment by IAmTheMilkManMyMilkIsDelicious** [comment]
I can check health status with the `docker ps` command. The `STATUS` column will say something like `Up 26 hours (healthy)`

I can also run `docker inspect -f '{{.State.Health.Status}}' mycontainer` which will return `healthy` or `unhealthy` if the container has a healthcheck, otherwise the command will fail.
